version: '1'
services: 
  mongo:
    # connection: mongodb://mongo:27017/
  image: mongo:5.0.1
  restart: unless-stopped
  volumes:
    - db_data:/data/db

  mongoAdmin:
    depends_on:
      - "mongo"
    image: mrvautin/adminmongo
    environment:
      - HOST=0.0.0.0
      - CONN_NAME=StreamOverlay
      - DB_NAME=StreamOverlay
      - DB_HOST=mongo
      - DB_PORT=27017
    ports:
      - "1234:1234"
  
  development:
    build: ./
    command: sleep infinity
    depends_on:
      - "mongo"
    environment:
      - NODE_ENV=development
      - NODE_PORT=3001
      - MONGODB=mongo:27017
    ports:
      - "3000:3000"
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - ..:/usr/src/app:cached
      - ~/.ssh:/home/node/.ssh

volumes:
  db_data: